#!/usr/bin/env bash
# Build the plugin's Python/CASA environment under ${CLAUDE_PLUGIN_DATA}.
#
#   ensure-env.sh --hook    SessionStart hook. Returns in well under a second:
#                           if the environment is stale or missing it starts a
#                           detached --build and tells the user and Claude so.
#   ensure-env.sh --build   Do the build (normally spawned detached; output
#                           goes to ${CLAUDE_PLUGIN_DATA}/build.log).
#
# The first build is a conda solve plus ~500 MB of casatools wheels, far past
# the MCP startup timeout, which is why it does not run inside the server
# launchers. Later builds (plugin update, same pixi.lock) only re-sync the
# sources and reuse the installed packages.
set -euo pipefail

# shellcheck source=scripts/plugin/env-lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/env-lib.sh"

json_escape() {
    sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' | tr '\n' ' '
}

# SessionStart output: systemMessage is shown to the user, additionalContext
# goes to Claude.
emit() {
    printf '{"systemMessage":"%s","hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"%s"}}\n' \
        "$(printf '%s' "$1" | json_escape)" "$(printf '%s' "$2" | json_escape)"
}

# Context for Claude only, nothing shown to the user.
emit_context() {
    printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"%s"}}\n' \
        "$(printf '%s' "$1" | json_escape)"
}

run_hook() {
    # Not running as an installed plugin (e.g. a clone with this hook wired
    # by hand): the launchers use the repo's own pixi environment instead.
    [[ -n "$RA_DATA" ]] || exit 0

    if ! ra_platform_supported; then
        emit "radio-analyst: this machine is $(ra_platform), but the plugin's Python/CASA environment builds only for ${RA_SUPPORTED_PLATFORMS[*]} (the platforms pixi.toml targets), so the ms-inspect / ms-modify / ms-create MCP servers cannot run here." \
            "The radio-analyst MCP servers (ms-inspect, ms-modify, ms-create) cannot run on this platform ($(ra_platform); supported: ${RA_SUPPORTED_PLATFORMS[*]}). No Measurement Set tool can be called in this session; say so if the user asks for one."
        exit 0
    fi

    if ! command -v pixi >/dev/null 2>&1; then
        emit "radio-analyst: pixi is not on PATH, so the ms-inspect / ms-modify / ms-create MCP servers cannot start. Install it (curl -fsSL https://pixi.sh/install.sh | bash), restart Claude Code, and the environment will build automatically." \
            "The radio-analyst MCP servers (ms-inspect, ms-modify, ms-create) are unavailable because pixi is not installed. If the user asks for a Measurement Set tool, tell them to install pixi from https://pixi.sh and restart Claude Code."
        exit 0
    fi

    # The write tools generate CASA scripts (execute=False) for Claude to run
    # with Bash, which does not see CLAUDE_PLUGIN_DATA. Hand Claude the
    # interpreter that has casatools/casatasks, once per session.
    if ra_ready; then
        emit_context "radio-analyst plugin: run Python/CASA scripts generated by the ms-modify / ms-create tools (and ms-simulator scripts) with this interpreter, which has casatools and casatasks installed: $(ra_prefix)/bin/python"
        exit 0
    fi

    ra_build_running || ra_spawn_build
    emit "radio-analyst: building the Python/CASA environment in the background (first run or plugin update; the first build downloads ~1 GB and can take several minutes). Log: $RA_LOG. When it finishes, reconnect the servers with /mcp." \
        "The radio-analyst MCP servers (ms-inspect, ms-modify, ms-create) are unavailable until their environment finishes building in the background (log: $RA_LOG). If the user asks for a Measurement Set tool before then, tell them the build is still running and that they can reconnect the servers with /mcp once it completes."
}

run_build() {
    [[ -n "$RA_DATA" ]] || { echo "CLAUDE_PLUGIN_DATA is not set" >&2; exit 1; }
    ra_platform_supported ||
        { echo "unsupported platform $(ra_platform); supported: ${RA_SUPPORTED_PLATFORMS[*]}" >&2; exit 1; }
    mkdir -p "$RA_DATA"

    if ! mkdir "$RA_LOCK" 2>/dev/null; then
        if ra_build_running; then
            echo "[$(date)] another build is already running; exiting"
            exit 0
        fi
        mkdir "$RA_LOCK" 2>/dev/null || exit 0
    fi
    RA_OWNER="$(ra_proc_token $$)"
    printf '%s\n' "$RA_OWNER" >"$RA_LOCK/owner.tmp"
    mv "$RA_LOCK/owner.tmp" "$RA_LOCK/owner"
    # Release only a lock this build still owns.
    trap '[[ "$(ra_lock_owner)" == "$RA_OWNER" ]] && rm -rf "$RA_LOCK"' EXIT

    # One build per log: keep the previous build's log as build.log.prev and
    # start this one empty. Truncate rather than rename, because a spawned
    # build's own stdout is build.log (opened for append).
    if [[ -s "$RA_LOG" ]]; then
        cp "$RA_LOG" "$RA_LOG.prev"
    fi
    : >"$RA_LOG"

    echo "=== [$(date)] radio-analyst environment build from $RA_ROOT"
    if ra_ready; then
        echo "environment already up to date"
        exit 0
    fi
    command -v pixi >/dev/null 2>&1 || { echo "pixi is not on PATH" >&2; exit 1; }

    local hash prefix
    hash="$(ra_source_hash)"

    # The environment is about to change in place. Until the new stamp is
    # written at the end, no reader may treat it as ready.
    rm -f "$RA_STAMP"

    # Sync the sources. app/.pixi is left in place so unchanged packages are
    # reused; src/ is replaced wholesale so deleted modules do not linger.
    mkdir -p "$RA_APP"
    for f in "${RA_COPY_FILES[@]}"; do
        cp "$RA_ROOT/$f" "$RA_APP/$f"
    done
    rm -rf "$RA_APP/src"
    cp -R "$RA_ROOT/src" "$RA_APP/src"
    find "$RA_APP/src" -name __pycache__ -prune -exec rm -rf {} +

    # --frozen: install exactly what pixi.lock pins, never re-solve.
    pixi install --manifest-path "$RA_APP/pixi.toml" --frozen
    prefix="$(pixi run --manifest-path "$RA_APP/pixi.toml" --frozen \
        python -c 'import sys; print(sys.prefix)')"

    # casatools is locked for linux-64 only; elsewhere install it with pip.
    # An environment without casatools is a failed build: no stamp is
    # written, so the next session retries.
    mkdir -p "$HOME/.casa/data"
    if ! "$prefix/bin/python" -c 'import casatools' 2>/dev/null; then
        echo "casatools not importable; trying pip install casatools casatasks"
        "$prefix/bin/python" -m pip install casatools casatasks --quiet ||
            echo "WARNING: pip install of casatools/casatasks failed"
        "$prefix/bin/python" -c 'import casatools' ||
            { echo "ERROR: casatools still not importable; build failed" >&2; exit 1; }
    fi

    # Write each file whole, and the stamp last: the stamp marks the
    # environment ready.
    printf '%s\n' "$prefix" >"$RA_PREFIX_FILE.tmp"
    mv "$RA_PREFIX_FILE.tmp" "$RA_PREFIX_FILE"
    printf '%s\n' "$hash" >"$RA_STAMP.tmp"
    mv "$RA_STAMP.tmp" "$RA_STAMP"
    echo "=== [$(date)] build complete: $prefix"
}

case "${1:-}" in
    --hook) run_hook ;;
    --build) run_build ;;
    *)
        echo "usage: $0 --hook | --build" >&2
        exit 2
        ;;
esac
