"""
bandpass.py — ms_bandpass

Solve for the complex bandpass calibration (channel-by-channel gains).
This is the final bandpass solve run after RFI flagging is complete,
distinct from the coarse initial_bandpass used to generate CORRECTED
for rflag.

CASA call sequence:
  bandpass(solint='inf', combine='scan', bandtype='B') → <caltable>

Hard fails if the caltable is not produced on disk.

When execute=False (default), writes a self-contained script to
workdir/<caltable_stem>.py and returns immediately.
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.util.casa_context import describe_numeric_fields, validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import normalize_field_sel, normalize_spw_sel, response_envelope
from ms_inspect.util.stage_log import record_stage
from ms_modify.exceptions import BandpassFailedError

TOOL_NAME = "ms_bandpass"

_BANDTYPE = "B"


def _script_path(workdir: Path, caltable: str) -> Path:
    stem = Path(caltable).name.replace(".", "_")
    return workdir / f"bandpass_{stem}.py"


def _build_script(
    ms_str: str,
    caltable: str,
    workdir: str,
    field: str,
    spw: str,
    solint: str,
    combine: str,
    refant: str,
    minsnr: float,
    minblperant: int,
    fillgaps: int,
    solnorm: bool,
    gaintable: list[str],
    interp: list[str],
    parang: bool,
) -> str:
    from ms_inspect.util.stage_log import RECORD_STAGE_SNIPPET as record
    from ms_modify.pathguard import SAFE_RM_TABLE_SNIPPET as safe_rm

    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_bandpass (ms_modify).
Run with: python bandpass_{Path(caltable).name.replace(".", "_")}.py
\"\"\"
import os
import shutil
from casatasks import bandpass

{safe_rm}
{record}
_safe_rm_table({caltable!r})
bandpass(
    vis={ms_str!r},
    caltable={caltable!r},
    field={field!r},
    spw={spw!r},
    solint={solint!r},
    combine={combine!r},
    refant={refant!r},
    minsnr={minsnr},
    minblperant={minblperant},
    bandtype={_BANDTYPE!r},
    fillgaps={fillgaps},
    solnorm={solnorm},
    gaintable={gaintable!r},
    interp={interp!r},
    parang={parang},
)
_record_stage({workdir!r}, "bandpass", {caltable!r})
print("Done. Caltable written to: {caltable}")
"""


def run(
    ms_path: str,
    field: str,
    spw: str,
    caltable: str,
    workdir: str,
    solint: str = "inf",
    combine: str = "scan",
    refant: str = "",
    minsnr: float = 3.0,
    minblperant: int = 4,
    fillgaps: int = 0,
    solnorm: bool = False,
    gaintable: list[str] | None = None,
    interp: list[str] | None = None,
    parang: bool = True,
    target_fields: str = "",
    execute: bool = False,
) -> dict:
    """
    Solve for the complex bandpass calibration.

    Args:
        ms_path:      Path to the Measurement Set.
        field:        CASA field selection for the bandpass calibrator.
        spw:          CASA SpW selection (empty = all).
        caltable:     Output caltable path.
        workdir:      Existing directory; script is written here.
        solint:       Solution interval (default 'inf').
        combine:      Data axes to combine (default 'scan').
        refant:       Reference antenna name.
        minsnr:       Minimum SNR threshold (default 3.0).
        minblperant:  Minimum baselines per antenna (default 4).
        fillgaps:     Fill flagged channels up to this width by interpolation
                      (default 0 — no gap filling for the final bandpass).
                      Use 62 for the initial coarse bandpass (ms_initial_bandpass).
        solnorm:      Normalise to unit amplitude (default False).
        gaintable:    Prior caltables to apply on-the-fly.
        interp:       Interpolation mode per gaintable entry.
        parang:       Apply parallactic angle correction (default True).
        target_fields: Optional CASA field selection for the science-target /
                      transfer fields, used only for the SpW-coverage guardrail.
                      Empty (default) infers them from intents; raises if it cannot.
        execute:      If False (default), write script and return.
                      If True, run bandpass in-process.

    Returns:
        Standard response envelope with script_path always present.
        When execute=True, also includes caltable.
    """
    field = normalize_field_sel(field)
    spw = normalize_spw_sel(spw)
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []
    warnings.extend(describe_numeric_fields(ms_path, field))

    from ms_inspect.util.spw_coverage import check_spw_coverage

    warnings.extend(check_spw_coverage(ms_str, field, spw, target_fields))

    if gaintable is None:
        gaintable = []
    if interp is None:
        interp = [""] * len(gaintable)

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"workdir does not exist: {workdir}",
            ms_path=ms_path,
        )

    from ms_modify.pathguard import validate_output_caltable

    validate_output_caltable(caltable, workdir, ms_str)

    for gt in gaintable:
        if not Path(gt).exists():
            from ms_inspect.exceptions import ComputationError

            raise ComputationError(
                f"Prior caltable not found: {gt}",
                ms_path=ms_path,
            )

    script = _script_path(workdir_path, caltable)
    script.write_text(
        _build_script(
            ms_str=ms_str,
            caltable=caltable,
            workdir=str(workdir_path),
            field=field,
            spw=spw,
            solint=solint,
            combine=combine,
            refant=refant,
            minsnr=minsnr,
            minblperant=minblperant,
            fillgaps=fillgaps,
            solnorm=solnorm,
            gaintable=gaintable,
            interp=interp,
            parang=parang,
        )
    )
    casa_calls.append(f"write_script → {script}")

    if not execute:
        warnings.append(
            f"Script written to {script}. Run it externally, "
            "then verify the caltable exists before proceeding."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data={
                "script_path": fmt_field(str(script)),
                "caltable": fmt_field(None, flag="UNAVAILABLE", note="script not yet executed"),
                "field": field,
                "spw": spw,
                "solint": solint,
                "combine": combine,
                "refant": refant,
                "fillgaps": fillgaps,
                "n_prior_tables": len(gaintable),
                "parang": parang,
            },
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True
    try:
        from casatasks import bandpass  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    casa_calls.append(
        f"casatasks.bandpass(field={field!r}, solint={solint!r}, "
        f"combine={combine!r}, refant={refant!r}, fillgaps={fillgaps}) → {caltable}"
    )

    try:
        bandpass(
            vis=ms_str,
            caltable=caltable,
            field=field,
            spw=spw,
            solint=solint,
            combine=combine,
            refant=refant,
            minsnr=minsnr,
            minblperant=minblperant,
            bandtype=_BANDTYPE,
            fillgaps=fillgaps,
            solnorm=solnorm,
            gaintable=gaintable,
            interp=interp,
            parang=parang,
        )
    except Exception as e:
        raise BandpassFailedError(
            f"bandpass raised an exception: {e}\n"
            f"Command: bandpass(vis={ms_str!r}, caltable={caltable!r}, "
            f"field={field!r}, solint={solint!r}, combine={combine!r})",
            ms_path=ms_path,
        ) from e

    # record_stage does the existence check and writes the stage-log line either
    # way; the domain error is re-raised over it so the caller keeps the
    # diagnostic message rather than a bare RuntimeError.
    try:
        record_stage(str(workdir_path), "bandpass", caltable)
    except RuntimeError as exc:
        raise BandpassFailedError(
            f"bandpass did not produce caltable at {caltable!r}. "
            "Possible causes: too few unflagged baselines, wrong field/spw selection, "
            f"or refant {refant!r} not present in the MS.",
            ms_path=ms_path,
        ) from exc

    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data={
            "script_path": fmt_field(str(script)),
            "caltable": fmt_field(caltable),
            "field": field,
            "spw": spw,
            "solint": solint,
            "combine": combine,
            "refant": refant,
            "fillgaps": fillgaps,
            "n_prior_tables": len(gaintable),
            "parang": parang,
        },
        warnings=warnings,
        casa_calls=casa_calls,
    )
