"""
fluxscale.py — ms_fluxscale

Bootstrap the flux density scale from a primary (reference) calibrator to
one or more secondary (transfer) calibrators. Reads the gain solutions in
caltable, computes the ratio between reference and transfer amplitudes, and
writes a new fluxtable with the rescaled solutions.

CASA call sequence:
  fluxscale(caltable=<gain.G>, fluxtable=<gain.fluxscaled>,
            reference=<flux_field>, transfer=[<phase_field>])

Hard fails if fluxtable is not produced on disk.

When execute=False (default), writes a self-contained script to
workdir/fluxscale.py and returns immediately.
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.util.casa_context import describe_numeric_fields, validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import response_envelope
from ms_inspect.util.stage_log import record_stage
from ms_modify.exceptions import FluxscaleFailedError

TOOL_NAME = "ms_fluxscale"


def _resolve_field_ids(caltable: str, names: list[str]) -> list[str]:
    """Map field names to the field IDs that actually carry solutions in caltable.

    Guards the duplicate-name case (an empty placeholder field sharing a name
    with the real one): only IDs present in the caltable's FIELD_ID are returned,
    so fluxscale gets an unambiguous id selection instead of a colliding name.
    """
    from ms_inspect.util.casa_context import open_table

    with open_table(str(Path(caltable) / "FIELD")) as tb:
        id_to_name = {i: str(n) for i, n in enumerate(tb.getcol("NAME"))}
    with open_table(caltable) as tb:
        present = {int(x) for x in tb.getcol("FIELD_ID")}
    out: list[str] = []
    for nm in names:
        ids = [fid for fid, fn in id_to_name.items() if fn == nm and fid in present]
        if ids:
            out.extend(str(fid) for fid in ids)
        else:
            out.append(nm)
    return out


def _build_script(
    ms_str: str,
    caltable: str,
    workdir: str,
    fluxtable: str,
    reference: str,
    transfer: list[str],
    incremental: bool,
) -> str:
    from ms_inspect.util.stage_log import RECORD_STAGE_SNIPPET as record
    from ms_modify.pathguard import SAFE_RM_TABLE_SNIPPET as safe_rm

    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_fluxscale (ms_modify).
Run with: python fluxscale.py
\"\"\"
import os
import shutil
from casatasks import fluxscale

{safe_rm}
{record}
_safe_rm_table({fluxtable!r})
result = fluxscale(
    vis={ms_str!r},
    caltable={caltable!r},
    fluxtable={fluxtable!r},
    reference={reference!r},
    transfer={transfer!r},
    incremental={incremental},
)
_record_stage({workdir!r}, "fluxscale", {fluxtable!r})
print("Done. Fluxtable written to: {fluxtable}")
print("fluxscale result:", result)
"""


def run(
    ms_path: str,
    caltable: str,
    fluxtable: str,
    reference: str,
    transfer: list[str],
    workdir: str,
    incremental: bool = False,
    execute: bool = False,
) -> dict:
    """
    Bootstrap flux density from primary to secondary calibrators.

    Args:
        ms_path:     Path to the Measurement Set.
        caltable:    Input gain table containing solutions for all calibrators
                     (output of ms_gaincal with all cal fields).
        fluxtable:   Output path for the flux-scaled gain table.
        reference:   Field name of the primary flux calibrator.
        transfer:    List of field names whose flux densities are to be derived.
        workdir:     Existing directory; script is written here.
        incremental: If True, fluxtable is used in addition to caltable at
                     applycal. If False (default), fluxtable replaces caltable.
        execute:     If False (default), write script and return.
                     If True, run fluxscale in-process.

    Returns:
        Standard response envelope. When execute=True, also includes
        derived_flux_jy per transfer field per SPW.
    """
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []
    _flux_fields = ",".join([reference, *transfer])
    warnings.extend(describe_numeric_fields(ms_path, _flux_fields))

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"workdir does not exist: {workdir}",
            ms_path=ms_path,
        )

    from ms_modify.pathguard import validate_output_caltable

    validate_output_caltable(fluxtable, workdir, ms_str)

    if not Path(caltable).exists():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"Input caltable not found: {caltable}. Run ms_gaincal first.",
            ms_path=ms_path,
        )

    # Resolve names → field IDs present in the caltable (handles duplicate names).
    reference = _resolve_field_ids(caltable, [reference])[0]
    transfer = _resolve_field_ids(caltable, transfer)

    script_path = str(workdir_path / "fluxscale.py")
    Path(script_path).write_text(
        _build_script(
            ms_str=ms_str,
            caltable=caltable,
            workdir=str(workdir_path),
            fluxtable=fluxtable,
            reference=reference,
            transfer=transfer,
            incremental=incremental,
        )
    )
    casa_calls.append(f"write_script → {script_path}")

    if not execute:
        warnings.append(
            f"Script written to {script_path}. Run it externally, "
            "then verify fluxtable exists before calling ms_applycal."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data={
                "script_path": fmt_field(script_path),
                "fluxtable": fmt_field(None, flag="UNAVAILABLE", note="script not yet executed"),
                "caltable": caltable,
                "reference": reference,
                "transfer": transfer,
                "incremental": incremental,
                "derived_flux_jy": fmt_field(
                    None, flag="UNAVAILABLE", note="script not yet executed"
                ),
            },
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True
    try:
        from casatasks import fluxscale  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    casa_calls.append(
        f"casatasks.fluxscale(caltable={caltable!r}, fluxtable={fluxtable!r}, "
        f"reference={reference!r}, transfer={transfer!r})"
    )

    try:
        result = fluxscale(
            vis=ms_str,
            caltable=caltable,
            fluxtable=fluxtable,
            reference=reference,
            transfer=transfer,
            incremental=incremental,
        )
    except Exception as e:
        raise FluxscaleFailedError(
            f"fluxscale raised an exception: {e}\n"
            f"Command: fluxscale(caltable={caltable!r}, reference={reference!r}, "
            f"transfer={transfer!r})",
            ms_path=ms_path,
        ) from e

    # record_stage does the existence check and writes the stage-log line either
    # way; the domain error is re-raised over it so the caller keeps the
    # diagnostic message rather than a bare RuntimeError.
    try:
        record_stage(str(workdir_path), "fluxscale", fluxtable)
    except RuntimeError as exc:
        raise FluxscaleFailedError(
            f"fluxscale did not produce fluxtable at {fluxtable!r}. "
            "Check that the reference field has solutions in the input caltable.",
            ms_path=ms_path,
        ) from exc

    # Extract flux densities from the returned dict for structured output.
    # result is keyed by field_id (str) → spw_id (str) → {'fluxd': array([I,Q,U,V])}
    derived: dict[str, dict] = {}
    if isinstance(result, dict):
        for fid, fdata in result.items():
            if not isinstance(fdata, dict):
                continue
            field_name = fdata.get("fieldName", fid)
            spw_fluxes: dict[str, float] = {}
            for key, val in fdata.items():
                if key in (
                    "fieldName",
                    "fitFluxd",
                    "fitFluxdErr",
                    "fitRefFreq",
                    "spidx",
                    "spidxerr",
                    "covarMat",
                ):
                    continue
                if isinstance(val, dict) and "fluxd" in val:
                    try:
                        stokes_i = float(val["fluxd"][0])
                        spw_fluxes[f"spw{key}"] = round(stokes_i, 4)
                    except (TypeError, IndexError, KeyError):
                        pass
            if spw_fluxes:
                derived[field_name] = spw_fluxes

    if not derived:
        warnings.append(
            "fluxscale returned no parseable flux densities. "
            "Inspect the fluxtable manually with plotms."
        )

    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data={
            "script_path": fmt_field(script_path),
            "fluxtable": fmt_field(fluxtable),
            "caltable": caltable,
            "reference": reference,
            "transfer": transfer,
            "incremental": incremental,
            "derived_flux_jy": fmt_field(derived)
            if derived
            else fmt_field(
                None, flag="PARTIAL", note="fluxscale returned no parseable flux densities"
            ),
        },
        warnings=warnings,
        casa_calls=casa_calls,
    )
