"""
gaincal.py — ms_gaincal

Solve for antenna-based gain calibration solutions. Covers four use cases
driven by gaintype and calmode:

  gaintype='K'           → delay solutions (one per antenna per SPW)
  gaintype='KCROSS'      → cross-hand delay (requires smodel=[1,0,1,0])
  gaintype='G', calmode='p'  → phase-only gains (initial phase for bandpass)
  gaintype='G', calmode='ap' → amplitude+phase gains (final gain calibration)

When execute=False (default), writes a self-contained script to
workdir/<caltable_stem>.py and returns immediately. The user runs it
externally; the caltable is then available for subsequent solve steps.
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.util.casa_context import describe_numeric_fields, validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import normalize_field_sel, normalize_spw_sel, response_envelope
from ms_inspect.util.stage_log import record_stage
from ms_modify.exceptions import GaincalFailedError

TOOL_NAME = "ms_gaincal"


def _script_path(workdir: Path, caltable: str) -> Path:
    stem = Path(caltable).name.replace(".", "_")
    return workdir / f"gaincal_{stem}.py"


def _build_script(
    ms_str: str,
    caltable: str,
    workdir: str,
    field: str,
    spw: str,
    gaintype: str,
    calmode: str,
    solint: str,
    combine: str,
    refant: str,
    minsnr: float,
    minblperant: int,
    solnorm: bool,
    gaintable: list[str],
    interp: list[str],
    parang: bool,
    smodel: list[float] | None = None,
    spwmap: list[list[int]] | None = None,
) -> str:
    from ms_inspect.util.stage_log import RECORD_STAGE_SNIPPET as record
    from ms_modify.pathguard import SAFE_RM_TABLE_SNIPPET as safe_rm

    smodel_line = f"    smodel={smodel!r},\n" if smodel is not None else ""
    spwmap_line = f"    spwmap={spwmap!r},\n" if spwmap is not None else ""
    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_gaincal (ms_modify).
Run with: python {Path(caltable).name.replace(".", "_")}.py
\"\"\"
import os
import shutil
from casatasks import gaincal

{safe_rm}
{record}
_safe_rm_table({caltable!r})
gaincal(
    vis={ms_str!r},
    caltable={caltable!r},
    field={field!r},
    spw={spw!r},
    gaintype={gaintype!r},
    calmode={calmode!r},
    solint={solint!r},
    combine={combine!r},
    refant={refant!r},
    minsnr={minsnr},
    minblperant={minblperant},
    solnorm={solnorm},
{smodel_line}    gaintable={gaintable!r},
    interp={interp!r},
{spwmap_line}    parang={parang},
)
_record_stage({workdir!r}, "gaincal", {caltable!r})
print("Done. Caltable written to: {caltable}")
"""


def run(
    ms_path: str,
    field: str,
    spw: str,
    caltable: str,
    workdir: str,
    gaintype: str = "G",
    calmode: str = "ap",
    solint: str = "inf",
    combine: str = "",
    refant: str = "",
    minsnr: float = 3.0,
    minblperant: int = 4,
    solnorm: bool = False,
    gaintable: list[str] | None = None,
    interp: list[str] | None = None,
    spwmap: list[list[int]] | None = None,
    parang: bool = True,
    smodel: list[float] | None = None,
    target_fields: str = "",
    execute: bool = False,
) -> dict:
    """
    Solve for antenna gain calibration solutions.

    Args:
        ms_path:      Path to the Measurement Set.
        field:        CASA field selection (e.g. '3C147' or '3C147,J0555+3948').
        spw:          CASA SpW/channel selection (e.g. '0:5~58' or '').
        caltable:     Output caltable path (must be inside workdir).
        workdir:      Existing directory; script is written here.
        gaintype:     'G' for complex gains, 'K' for delays, 'KCROSS' for cross-hand delay.
        calmode:      'p' phase-only, 'a' amp-only, 'ap' amplitude+phase.
        solint:       Solution interval ('int', 'inf', or e.g. '60s').
        combine:      Data axes to combine ('scan', '' etc.).
        refant:       Reference antenna name.
        minsnr:       Minimum SNR for a valid solution (default 3.0).
        minblperant:  Minimum baselines per antenna (default 4).
        solnorm:      Normalise solutions to unit amplitude (default False).
        gaintable:    Prior caltables to apply on-the-fly.
        interp:       Interpolation mode per gaintable entry.
        spwmap:       Optional per-prior-table SPW map (list-of-lists aligned to
                      gaintable) to fan an spw-combined prior across all SPWs.
                      Default None → CASA identity. Only needed if a prior used
                      combine='spw' (a VLA multiband-delay choice).
        parang:       Apply parallactic angle correction (default True).
        smodel:       Scratch model [I, Q, U, V] for gaintype='KCROSS' (default None).
        target_fields: Optional CASA field selection for the science-target /
                      transfer fields, used only for the SpW-coverage guardrail.
                      Empty (default) infers them from intents; raises if it cannot.
        execute:      If False (default), write script and return.
                      If True, run gaincal in-process.

    Returns:
        Standard response envelope with script_path always present.
        When execute=True, also includes caltable and n_solutions.
    """
    field = normalize_field_sel(field)
    spw = normalize_spw_sel(spw)
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []
    warnings.extend(describe_numeric_fields(ms_path, field))

    from ms_inspect.util.spw_coverage import check_spw_coverage

    warnings.extend(check_spw_coverage(ms_str, field, spw, target_fields))

    if gaintable is None:
        gaintable = []
    if interp is None:
        interp = [""] * len(gaintable)

    if spwmap is not None and len(spwmap) != len(gaintable):
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"spwmap length ({len(spwmap)}) must match gaintable length ({len(gaintable)}). "
            "Pass a per-table list-of-lists, e.g. [[], [0,0,0,0]].",
            ms_path=ms_path,
        )

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"workdir does not exist: {workdir}",
            ms_path=ms_path,
        )

    from ms_modify.pathguard import validate_output_caltable

    validate_output_caltable(caltable, workdir, ms_str)

    for gt in gaintable:
        if not Path(gt).exists():
            from ms_inspect.exceptions import ComputationError

            raise ComputationError(
                f"Prior caltable not found: {gt}",
                ms_path=ms_path,
            )

    script = _script_path(workdir_path, caltable)
    script.write_text(
        _build_script(
            ms_str=ms_str,
            caltable=caltable,
            workdir=str(workdir_path),
            field=field,
            spw=spw,
            gaintype=gaintype,
            calmode=calmode,
            solint=solint,
            combine=combine,
            refant=refant,
            minsnr=minsnr,
            minblperant=minblperant,
            solnorm=solnorm,
            gaintable=gaintable,
            interp=interp,
            parang=parang,
            smodel=smodel,
            spwmap=spwmap,
        )
    )
    casa_calls.append(f"write_script → {script}")

    if not execute:
        warnings.append(
            f"Script written to {script}. Run it externally, "
            "then verify the caltable exists before proceeding."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data={
                "script_path": fmt_field(str(script)),
                "caltable": fmt_field(None, flag="UNAVAILABLE", note="script not yet executed"),
                "gaintype": gaintype,
                "calmode": calmode,
                "solint": solint,
                "combine": combine,
                "refant": refant,
                "field": field,
                "spw": spw,
                "n_prior_tables": len(gaintable),
                "parang": parang,
            },
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True
    try:
        from casatasks import gaincal  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    casa_calls.append(
        f"casatasks.gaincal(field={field!r}, gaintype={gaintype!r}, "
        f"calmode={calmode!r}, solint={solint!r}, refant={refant!r}) → {caltable}"
    )

    kwargs = dict(
        vis=ms_str,
        caltable=caltable,
        field=field,
        spw=spw,
        gaintype=gaintype,
        calmode=calmode,
        solint=solint,
        combine=combine,
        refant=refant,
        minsnr=minsnr,
        minblperant=minblperant,
        solnorm=solnorm,
        gaintable=gaintable,
        interp=interp,
        parang=parang,
    )
    if smodel is not None:
        kwargs["smodel"] = smodel
    if spwmap is not None:
        kwargs["spwmap"] = spwmap
    try:
        gaincal(**kwargs)
    except Exception as e:
        raise GaincalFailedError(
            f"gaincal raised an exception: {e}\n"
            f"Command: gaincal(vis={ms_str!r}, caltable={caltable!r}, "
            f"field={field!r}, gaintype={gaintype!r}, calmode={calmode!r})",
            ms_path=ms_path,
        ) from e

    # record_stage does the existence check and writes the stage-log line either
    # way; the domain error is re-raised over it so the caller keeps the
    # diagnostic message rather than a bare RuntimeError.
    try:
        record_stage(str(workdir_path), "gaincal", caltable)
    except RuntimeError as exc:
        raise GaincalFailedError(
            f"gaincal did not produce caltable at {caltable!r}. "
            "Possible causes: too few unflagged baselines, wrong field/spw selection, "
            f"or refant {refant!r} not present in the MS.",
            ms_path=ms_path,
        ) from exc

    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data={
            "script_path": fmt_field(str(script)),
            "caltable": fmt_field(caltable),
            "gaintype": gaintype,
            "calmode": calmode,
            "solint": solint,
            "combine": combine,
            "refant": refant,
            "field": field,
            "spw": spw,
            "n_prior_tables": len(gaintable),
            "parang": parang,
        },
        warnings=warnings,
        casa_calls=casa_calls,
    )
