"""
polcal.py — ms_polcal

Solve for polarisation calibration solutions. Supports three poltype modes:

  poltype='Df'    → D-term leakage calibration (source polarisation unknown).
  poltype='Df+QU' → D-term leakage + source Q,U (both unknowns solved together).
  poltype='Xf'    → Position angle calibration (requires angle cal model set via setjy).

When execute=False (default), writes a self-contained script to
workdir/polcal_<caltable_stem>.py and returns immediately. The user runs it
externally; the caltable is then available for subsequent solve steps.
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.util.casa_context import describe_numeric_fields, validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import normalize_field_sel, response_envelope
from ms_inspect.util.stage_log import record_stage
from ms_modify.exceptions import PolcalFailedError

TOOL_NAME = "ms_polcal"


def _script_path(workdir: Path, caltable: str) -> Path:
    stem = Path(caltable).name.replace(".", "_")
    return workdir / f"polcal_{stem}.py"


def _build_script(
    ms_str: str,
    caltable: str,
    workdir: str,
    field: str,
    poltype: str,
    solint: str,
    combine: str,
    refant: str,
    gaintable: list[str],
    interp: list[str],
    parang: bool,
    spwmap: list[list[int]] | None = None,
) -> str:
    from ms_inspect.util.stage_log import RECORD_STAGE_SNIPPET as record
    from ms_modify.pathguard import SAFE_RM_TABLE_SNIPPET as safe_rm

    spwmap_line = f"    spwmap={spwmap!r},\n" if spwmap is not None else ""
    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_polcal (ms_modify).
Run with: python {Path(caltable).name.replace(".", "_")}.py
\"\"\"
import os
import shutil
from casatasks import polcal

{safe_rm}
{record}
_safe_rm_table({caltable!r})
polcal(
    vis={ms_str!r},
    caltable={caltable!r},
    field={field!r},
    poltype={poltype!r},
    solint={solint!r},
    combine={combine!r},
    refant={refant!r},
    gaintable={gaintable!r},
    interp={interp!r},
{spwmap_line})
_record_stage({workdir!r}, "polcal", {caltable!r})
print("Done. Caltable written to: {caltable}")
"""


def run(
    ms_path: str,
    field: str,
    caltable: str,
    workdir: str,
    poltype: str,
    solint: str = "inf",
    combine: str = "scan",
    refant: str = "",
    gaintable: list[str] | None = None,
    interp: list[str] | None = None,
    spwmap: list[list[int]] | None = None,
    parang: bool = True,
    target_fields: str = "",
    execute: bool = False,
) -> dict:
    """
    Solve for polarisation calibration solutions.

    Args:
        ms_path:      Path to the Measurement Set.
        field:        CASA field selection for calibrator.
        caltable:     Output caltable path.
        workdir:      Existing directory; script is written here.
        poltype:      'Df' (D-terms), 'Df+QU' (D-terms + source pol), or 'Xf' (position angle).
        solint:       Solution interval (default 'inf').
        combine:      Data axes to combine (default 'scan').
        refant:       Reference antenna name.
        gaintable:    Prior caltables to apply on-the-fly.
        interp:       Interpolation mode per gaintable entry.
        spwmap:       Optional per-prior-table SPW map (list-of-lists aligned to
                      gaintable), e.g. [[], [0,0,0,0]] to fan an spw-combined prior
                      (a VLA multiband-delay Kcross) across all SPWs. Default None →
                      CASA identity. Only needed if a prior used combine='spw'.
        target_fields: Optional CASA field selection for the science-target /
                      transfer fields, used only for the SpW-coverage guardrail.
                      Empty (default) infers them from intents; raises if it cannot.
        execute:      If False (default), write script and return.
                      If True, run polcal in-process.

    Returns:
        Standard response envelope with script_path always present.
        When execute=True, also includes caltable path.
    """
    field = normalize_field_sel(field)
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []
    warnings.extend(describe_numeric_fields(ms_path, field))

    # SpW-coverage guardrail: polcal solves on the pol calibrator and the table is
    # applied to the target/transfer fields. polcal has no spw selection (solves all
    # SpWs), so pass '' for the selection.
    from ms_inspect.util.spw_coverage import check_spw_coverage

    warnings.extend(check_spw_coverage(ms_str, field, "", target_fields))

    if poltype not in ("Df", "Df+QU", "Xf"):
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"poltype must be 'Df', 'Df+QU', or 'Xf'; got {poltype!r}",
            ms_path=ms_path,
        )

    if gaintable is None:
        gaintable = []
    if interp is None:
        interp = [""] * len(gaintable)

    if spwmap is not None and len(spwmap) != len(gaintable):
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"spwmap length ({len(spwmap)}) must match gaintable length ({len(gaintable)}). "
            "Pass a per-table list-of-lists, e.g. [[], [0,0,0,0]].",
            ms_path=ms_path,
        )

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"workdir does not exist: {workdir}",
            ms_path=ms_path,
        )

    from ms_modify.pathguard import validate_output_caltable

    validate_output_caltable(caltable, workdir, ms_str)

    for gt in gaintable:
        if not Path(gt).exists():
            from ms_inspect.exceptions import ComputationError

            raise ComputationError(
                f"Prior caltable not found: {gt}",
                ms_path=ms_path,
            )

    script = _script_path(workdir_path, caltable)
    script.write_text(
        _build_script(
            ms_str=ms_str,
            caltable=caltable,
            workdir=str(workdir_path),
            field=field,
            poltype=poltype,
            solint=solint,
            combine=combine,
            refant=refant,
            gaintable=gaintable,
            interp=interp,
            parang=parang,
            spwmap=spwmap,
        )
    )
    casa_calls.append(f"write_script → {script}")

    if not execute:
        warnings.append(
            f"Script written to {script}. Run it externally, "
            "then verify the caltable exists before proceeding."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data={
                "script_path": fmt_field(str(script)),
                "caltable": fmt_field(None, flag="UNAVAILABLE", note="script not yet executed"),
                "poltype": poltype,
                "field": field,
                "solint": solint,
                "combine": combine,
                "refant": refant,
                "n_prior_tables": len(gaintable),
                "parang": parang,
            },
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True
    try:
        from casatasks import polcal  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    casa_calls.append(
        f"casatasks.polcal(field={field!r}, poltype={poltype!r}, "
        f"solint={solint!r}, refant={refant!r}) → {caltable}"
    )

    try:
        # NOTE: casatasks.polcal does not accept a `parang` argument — it applies
        # the parallactic-angle correction internally per poltype. Passing parang
        # raises TypeError. The `parang` run() arg is retained for API symmetry
        # with gaincal/bandpass/applycal but is not forwarded here.
        polcal_kwargs: dict = dict(
            vis=ms_str,
            caltable=caltable,
            field=field,
            poltype=poltype,
            solint=solint,
            combine=combine,
            refant=refant,
            gaintable=gaintable,
            interp=interp,
        )
        if spwmap is not None:
            polcal_kwargs["spwmap"] = spwmap
        polcal(**polcal_kwargs)
    except Exception as e:
        raise PolcalFailedError(
            f"polcal raised an exception: {e}\n"
            f"Command: polcal(vis={ms_str!r}, caltable={caltable!r}, "
            f"field={field!r}, poltype={poltype!r})",
            ms_path=ms_path,
        ) from e

    # record_stage does the existence check and writes the stage-log line either
    # way; the domain error is re-raised over it so the caller keeps the
    # diagnostic message rather than a bare RuntimeError.
    try:
        record_stage(str(workdir_path), "polcal", caltable)
    except RuntimeError as exc:
        raise PolcalFailedError(
            f"polcal did not produce caltable at {caltable!r}. "
            f"Possible causes: too few unflagged data, insufficient parallactic angle coverage, "
            f"or refant {refant!r} not present in the MS.",
            ms_path=ms_path,
        ) from exc

    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data={
            "script_path": fmt_field(str(script)),
            "caltable": fmt_field(caltable),
            "poltype": poltype,
            "field": field,
            "solint": solint,
            "combine": combine,
            "refant": refant,
            "n_prior_tables": len(gaintable),
            "parang": parang,
        },
        warnings=warnings,
        casa_calls=casa_calls,
    )
