"""
rflag.py — ms_apply_rflag

Generates (and optionally executes) an rflag flagging script on the
CORRECTED column of a calibrator-only MS.

When execute=False (default), writes workdir/apply_rflag.py and returns
immediately. The user runs the script externally; ms_flag_summary can then
capture the before/after flag fraction delta.
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.util.casa_context import validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import normalize_field_sel, normalize_spw_sel, response_envelope
from ms_inspect.util.stage_log import record_stage

TOOL_NAME = "ms_apply_rflag"


def _build_script(
    ms_str: str,
    field_sel: str,
    spw: str,
    datacolumn: str,
    timedevscale: float,
    freqdevscale: float,
    workdir: str,
) -> str:
    """Return a self-contained rflag Python script."""
    from ms_inspect.util.stage_log import RECORD_STAGE_SNIPPET as record

    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_apply_rflag (ms_modify).
Run with: python apply_rflag.py
\"\"\"
from casatasks import flagdata, flagmanager

{record}

ms_path = {ms_str!r}
workdir = {workdir!r}

# Save a flag backup before applying
flagmanager(
    vis=ms_path,
    mode="save",
    versionname="before_rflag",
    comment="Flag state before ms_apply_rflag",
)

# Apply rflag on CORRECTED column
flagdata(
    vis=ms_path,
    mode="rflag",
    action="apply",
    field={field_sel!r},
    spw={spw!r},
    datacolumn={datacolumn!r},
    timedevscale={timedevscale},
    freqdevscale={freqdevscale},
    flagbackup=False,
)
# flagdata(action='apply') returns nothing useful, so completion is measured
# with a summary pass. It reports the flagged fraction the stage produced —
# a number, not a verdict — so a pass that flagged nothing is visible in the
# record instead of looking identical to one that worked.
_summary = flagdata(vis={ms_str!r}, mode="summary")
_flagged = (
    float(_summary["flagged"]) / float(_summary["total"]) if _summary.get("total") else None
)
_record_stage({workdir!r}, "rflag", {ms_str!r}, {{"flagged_fraction": _flagged}})
print("Done. Flags applied. Use ms_flag_summary to inspect the result.")
"""


def run(
    ms_path: str,
    workdir: str,
    field: str = "",
    spw: str = "",
    datacolumn: str = "corrected",
    timedevscale: float = 5.0,
    freqdevscale: float = 5.0,
    execute: bool = False,
) -> dict:
    """
    Generate (and optionally execute) an rflag script on the CORRECTED column.

    Args:
        ms_path:      Path to the MS (CORRECTED column must exist).
        workdir:      Directory for the generated script and flag backups.
        field:        CASA field selection (empty = all).
        spw:          CASA SpW selection (empty = all).
        datacolumn:   Column to flag on (default 'corrected').
        timedevscale: rflag time deviation scale threshold (default 5.0).
        freqdevscale: rflag frequency deviation scale threshold (default 5.0).
        execute:      If False (default), write script and return immediately.
                      If True, run rflag in-process (may take several minutes).

    Returns:
        Standard response envelope with script_path always present.
    """
    field = normalize_field_sel(field)
    spw = normalize_spw_sel(spw)
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"workdir does not exist: {workdir}. Create it before calling this tool.",
            ms_path=ms_path,
        )

    script_path = str(workdir_path / "apply_rflag.py")

    # Always write script
    script_content = _build_script(
        ms_str=ms_str,
        field_sel=field,
        spw=spw,
        datacolumn=datacolumn,
        timedevscale=timedevscale,
        freqdevscale=freqdevscale,
        workdir=workdir,
    )
    Path(script_path).write_text(script_content)
    casa_calls.append(f"write_script → {script_path}")

    base_data = {
        "script_path": fmt_field(script_path),
        "datacolumn": datacolumn,
        "timedevscale": timedevscale,
        "freqdevscale": freqdevscale,
        "field": field,
        "spw": spw,
    }

    if not execute:
        warnings.append(
            f"Script written to {script_path}. Run it externally, "
            "then call ms_flag_summary to compare before/after flag fractions."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data=base_data,
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True: run in-process
    try:
        from casatasks import flagdata, flagmanager  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    # Save flag backup before applying
    try:
        flagmanager(
            vis=ms_str,
            mode="save",
            versionname="before_rflag",
            comment="Flag state before ms_apply_rflag",
        )
        casa_calls.append("casatasks.flagmanager(vis=..., mode='save', versionname='before_rflag')")
    except Exception as exc:
        warnings.append(f"Could not save flag backup: {exc}. Proceeding without backup.")

    # Apply rflag
    casa_calls.append(
        f"casatasks.flagdata(mode='rflag', action='apply', "
        f"datacolumn='{datacolumn}', timedevscale={timedevscale}, freqdevscale={freqdevscale})"
    )
    try:
        flagdata(
            vis=ms_str,
            mode="rflag",
            action="apply",
            field=field,
            spw=spw,
            datacolumn=datacolumn,
            timedevscale=timedevscale,
            freqdevscale=freqdevscale,
            flagbackup=False,
        )
    except Exception as exc:
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"flagdata(mode='rflag', action='apply') failed: {exc}",
            ms_path=ms_path,
        ) from exc

    # flagdata(action='apply') returns nothing useful, so measure the flagged
    # fraction the pass produced instead of asserting that it worked.
    summary = flagdata(vis=ms_str, mode="summary")
    total = float(summary.get("total") or 0.0)
    flagged_fraction = float(summary["flagged"]) / total if total else None
    record_stage(
        str(workdir_path),
        "rflag",
        ms_str,
        {"flagged_fraction": flagged_fraction},
    )

    base_data["flags_applied"] = fmt_field(True)
    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data=base_data,
        warnings=warnings,
        casa_calls=casa_calls,
    )
