"""
setjy_polcal.py — ms_setjy_polcal

Sets the full polarization model (Stokes I + polindex + polangle) for a
polarization angle calibrator using setjy(standard='manual').

Two data sources, combined (mirrors the NRAO CASA polarization guide):
  - Stokes I (flux at reffreq + spix): probed from CASA's own Perley-Butler
    flux standard. setjy(standard='Perley-Butler 2017', usescratch=False)
    returns the model flux per SPW; we run it per SPW (equipartitioning a wide
    SPW into chunks no smaller than min_chunk_mhz) and fit log10(S) vs
    log10(f/f_ref). The pol-property catalogue tables (e.g. the 2019 NRAO
    epoch) carry NO Stokes I, so it cannot come from there.
  - polindex / polangle: fit from the pol-property catalogue (pure numpy,
    no CASA), embedded into the script as literal coefficient lists.

Logic:
  1. Fit polindex/polangle from the catalogue (generation time, no CASA).
  2. Generate a self-contained script that, at run time:
       a. discovers the calibrator's SPWs via msmd and builds probe selections
          (each chunk ≥ min_chunk_mhz),
       b. runs setjy(standard='Perley-Butler 2017', usescratch=False) per chunk
          and harvests Stokes I,
       c. fits flux@reffreq + spix,
       d. runs setjy(standard='manual', ...) with the fitted I/spix and the
          embedded polindex/polangle.
  3. Optionally run the same probe→fit→apply in-process when execute=True.

CASA coefficient convention (ascending order):
  polindex = [c0, c1, c2, ...]   where c0 = fractional pol at reffreq
  polangle = [c0, c1, c2, ...]   where c0 = pol angle (radians) at reffreq
"""

from __future__ import annotations

from datetime import UTC
from pathlib import Path

from ms_inspect.exceptions import ComputationError
from ms_inspect.util.casa_context import open_table, validate_ms_path
from ms_inspect.util.conversions import mjd_seconds_to_unix
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import response_envelope
from ms_inspect.util.polcal_setjy_fit import (
    fit_pol_terms_from_catalogue,
    fit_stokes_i_adaptive,
    resolve_epoch,
)
from ms_inspect.util.stage_log import RECORD_STAGE_SNIPPET, record_stage

TOOL_NAME = "ms_setjy_polcal"

_PB_STANDARD = "Perley-Butler 2017"
_DEFAULT_MIN_CHUNK_MHZ = 32.0


def _read_band_range_ghz(ms_str: str) -> tuple[float, float]:
    """Return (lo, hi) GHz spanning all channels of all spectral windows.

    setjy spix/polindex/polangle are per-band local expansions, so the fits must
    be restricted to the observed band — not the catalogue's full 1–48 GHz span.
    """
    import numpy as np

    los: list[float] = []
    his: list[float] = []
    with open_table(ms_str + "/SPECTRAL_WINDOW") as tb:
        for i in range(tb.nrows()):
            cf = tb.getcell("CHAN_FREQ", i)
            los.append(float(np.min(cf)))
            his.append(float(np.max(cf)))
    return min(los) / 1e9, max(his) / 1e9


def _read_obs_year(ms_str: str) -> float | None:
    """Return the decimal observation year from OBSERVATION.TIME_RANGE, or None."""
    from datetime import datetime

    try:
        with open_table(ms_str + "/OBSERVATION") as tb:
            tr = tb.getcell("TIME_RANGE", 0)  # MJD seconds [start, end]
        mid_unix = mjd_seconds_to_unix((float(tr[0]) + float(tr[1])) / 2.0)
        dt = datetime.fromtimestamp(mid_unix, tz=UTC)
        y0 = datetime(dt.year, 1, 1, tzinfo=UTC)
        y1 = datetime(dt.year + 1, 1, 1, tzinfo=UTC)
        return dt.year + (dt - y0).total_seconds() / (y1 - y0).total_seconds()
    except Exception:
        return None


def _build_script(
    ms_str: str,
    field: str,
    calibrator: str,
    reffreq_ghz: float,
    polindex: list[float],
    polangle: list[float],
    min_chunk_mhz: float,
    workdir: str,
) -> str:
    """Return a self-contained CASA setjy script for polarization model setting."""
    record = RECORD_STAGE_SNIPPET
    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_setjy_polcal (ms_modify).
Run with: python setjy_polcal.py

Polarization angle calibrator: {calibrator} (field {field!r})
Reference frequency: {reffreq_ghz} GHz

Stokes I (flux@reffreq + spix) is probed from CASA's Perley-Butler 2017 flux
standard at run time. polindex/polangle below were fit from the pol-property
catalogue at generation time and are fixed.
\"\"\"
import numpy as np
from casatools import msmetadata
from casatasks import setjy

{record}

ms_path = {ms_str!r}
field = {field!r}
reffreq_ghz = {reffreq_ghz!r}
min_chunk_mhz = {min_chunk_mhz!r}

# Polarization terms (ascending order), from the catalogue:
polindex = {polindex!r}
polangle = {polangle!r}


def _probe_selections():
    \"\"\"Discover SPWs for the field and split wide SPWs into chunks >= min_chunk_mhz.

    Returns a list of (spw_selection_string, mean_freq_ghz).
    \"\"\"
    msmd = msmetadata()
    msmd.open(ms_path)
    try:
        spws = sorted(int(s) for s in msmd.spwsforfield(field))
        sels = []
        for spw in spws:
            chan_hz = np.asarray(msmd.chanfreqs(spw), dtype=float)
            nchan = chan_hz.size
            if nchan == 0:
                continue
            total_mhz = (chan_hz.max() - chan_hz.min()) / 1e6
            nchunks = max(1, int(total_mhz // min_chunk_mhz))
            nchunks = min(nchunks, nchan)  # never more chunks than channels
            edges = np.linspace(0, nchan, nchunks + 1, dtype=int)
            for i in range(nchunks):
                c0, c1 = int(edges[i]), int(edges[i + 1]) - 1
                if c1 < c0:
                    continue
                sels.append((f"{{spw}}:{{c0}}~{{c1}}", float(chan_hz[c0:c1 + 1].mean()) / 1e9))
        return sels
    finally:
        msmd.close()


def _extract_stokes_i(ret):
    \"\"\"Pull the Stokes I flux density (fluxd[0]) from a setjy return dict.\"\"\"
    for key, val in ret.items():
        if not isinstance(val, dict):
            continue
        for subkey, sub in val.items():
            if isinstance(sub, dict) and "fluxd" in sub:
                return float(sub["fluxd"][0])
    raise RuntimeError(f"Could not find fluxd in setjy return: {{ret!r}}")


# --- Probe Perley-Butler Stokes I per chunk ---
selections = _probe_selections()
freqs_ghz, fluxes_jy = [], []
for sel, fghz in selections:
    ret = setjy(
        vis=ms_path,
        field=field,
        spw=sel,
        standard={_PB_STANDARD!r},
        usescratch=False,
    )
    fluxes_jy.append(_extract_stokes_i(ret))
    freqs_ghz.append(fghz)

freqs = np.asarray(freqs_ghz, dtype=float)
flux = np.asarray(fluxes_jy, dtype=float)

# --- Fit log-polynomial Stokes I (degree adapts to number of samples) ---
x = np.log10(freqs / reffreq_ghz)
y = np.log10(flux)
deg = min(2, freqs.size - 1)
A = np.vander(x, deg + 1, increasing=True)
coeffs, _, _, _ = np.linalg.lstsq(A, y, rcond=None)
flux_at_ref = float(10.0 ** coeffs[0])
spix = [float(c) for c in coeffs[1:]] if deg >= 1 else [0.0]

print(f"Probed {{freqs.size}} freq points; I@{{reffreq_ghz}}GHz = {{flux_at_ref:.4f}} Jy, spix = {{spix}}")

# --- Apply the full polarized manual model ---
setjy(
    vis=ms_path,
    field={field!r},
    standard="manual",
    fluxdensity=[flux_at_ref, 0, 0, 0],
    spix=spix,
    reffreq=f"{{reffreq_ghz}}GHz",
    polindex=polindex,
    polangle=polangle,
    scalebychan=True,
    usescratch=True,
)
_record_stage(
    {workdir!r},
    "setjy_polcal",
    ms_path,
    {{"flux_jy": float(flux_at_ref), "spix": spix, "n_probe_points": int(freqs.size)}},
)
print("setjy polcal complete.")
"""


def _probe_stokes_i_in_process(
    ms_str: str, field: str, min_chunk_mhz: float
) -> tuple[list[float], list[float], list[str]]:
    """Run the Perley-Butler probe in-process. Returns (freqs_ghz, flux_jy, casa_calls)."""
    import numpy as np
    from casatasks import setjy

    from ms_inspect.util.casa_context import open_msmd

    casa_calls: list[str] = []
    selections: list[tuple[str, float]] = []
    with open_msmd(ms_str) as msmd:
        spws = sorted(int(s) for s in msmd.spwsforfield(field))
        for spw in spws:
            chan_hz = np.asarray(msmd.chanfreqs(spw), dtype=float)
            nchan = chan_hz.size
            if nchan == 0:
                continue
            total_mhz = (chan_hz.max() - chan_hz.min()) / 1e6
            nchunks = max(1, int(total_mhz // min_chunk_mhz))
            nchunks = min(nchunks, nchan)
            edges = np.linspace(0, nchan, nchunks + 1, dtype=int)
            for i in range(nchunks):
                c0, c1 = int(edges[i]), int(edges[i + 1]) - 1
                if c1 < c0:
                    continue
                selections.append((f"{spw}:{c0}~{c1}", float(chan_hz[c0 : c1 + 1].mean()) / 1e9))

    freqs: list[float] = []
    fluxes: list[float] = []
    for sel, fghz in selections:
        ret = setjy(vis=ms_str, field=field, spw=sel, standard=_PB_STANDARD, usescratch=False)
        casa_calls.append(
            f"casatasks.setjy(field='{field}', spw='{sel}', standard='{_PB_STANDARD}')"
        )
        fluxes.append(_extract_stokes_i_dict(ret))
        freqs.append(fghz)
    return freqs, fluxes, casa_calls


def _extract_stokes_i_dict(ret: dict) -> float:
    """Pull Stokes I (fluxd[0]) from a setjy return dict (in-process variant)."""
    for val in ret.values():
        if not isinstance(val, dict):
            continue
        for sub in val.values():
            if isinstance(sub, dict) and "fluxd" in sub:
                return float(sub["fluxd"][0])
    raise ComputationError(f"Could not find fluxd in setjy return: {ret!r}")


def run(
    ms_path: str,
    field: str,
    workdir: str,
    reffreq_ghz: float,
    calibrator_name: str | None = None,
    epoch: str | None = None,
    pol_freq_range_lo_ghz: float | None = None,
    pol_freq_range_hi_ghz: float | None = None,
    polindex_deg: int = 3,
    polangle_deg: int = 4,
    min_chunk_mhz: float = _DEFAULT_MIN_CHUNK_MHZ,
    execute: bool = False,
) -> dict:
    """
    Set the full polarization model for a polarization angle calibrator.

    Stokes I (flux + spectral index) is probed from CASA's Perley-Butler 2017
    flux standard at run time; polindex/polangle are fit from the pol-property
    catalogue. See module docstring for the rationale.

    Args:
        ms_path:              Path to the Measurement Set.
        field:                CASA field selection string (e.g. '3C48').
        workdir:              Existing directory to write setjy_polcal.py into.
        reffreq_ghz:          Reference frequency (GHz) for the polynomial expansion.
        calibrator_name:      Catalogue name to look up (defaults to field if None).
        epoch:                Catalogue epoch key. Default None auto-selects the
                              epoch nearest the observation date (latest if no
                              obs date is supplied).
        pol_freq_range_lo_ghz: Lower bound (GHz) to restrict pol fits.
        pol_freq_range_hi_ghz: Upper bound (GHz) to restrict pol fits.
        polindex_deg:          Degree of polindex polynomial (default 3).
        polangle_deg:          Degree of polangle polynomial (default 4).
        min_chunk_mhz:         Minimum width (MHz) of each Perley-Butler probe
                               chunk when equipartitioning a wide SPW (default 32).
        execute:               If False (default), write script only.
                               If True, run the probe→fit→apply in-process.

    Returns:
        Standard response envelope with script_path, calibrator, reffreq_ghz,
        polindex/polangle coefficient arrays, and (when execute=True) the
        probed flux_jy and spix.
    """
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        raise ComputationError(
            f"workdir does not exist: {workdir}. Create it before calling this tool.",
            ms_path=ms_path,
        )

    lookup_name = calibrator_name or field

    # Restrict all fits to the observed band (spix/polindex/polangle are per-band
    # local expansions about reffreq, not global wideband fits).
    try:
        band_lo, band_hi = _read_band_range_ghz(ms_str)
        casa_calls.append("tb.open(SPECTRAL_WINDOW) → CHAN_FREQ (band range)")
    except Exception as exc:
        band_lo = band_hi = None
        warnings.append(
            f"Could not read spectral window band range ({exc}); "
            "fits will use the full catalogue range (NOT per-band)."
        )

    flux_freq_range = (band_lo, band_hi) if band_lo is not None else None

    # Explicit caller override for the pol fits; otherwise default to the band.
    if pol_freq_range_lo_ghz is not None and pol_freq_range_hi_ghz is not None:
        pol_freq_range: tuple[float, float] | None = (pol_freq_range_lo_ghz, pol_freq_range_hi_ghz)
    else:
        pol_freq_range = flux_freq_range

    if band_lo is not None and not (band_lo <= reffreq_ghz <= band_hi):
        warnings.append(
            f"reffreq {reffreq_ghz} GHz is outside the observed band "
            f"({band_lo:.3f}–{band_hi:.3f} GHz); spix is extrapolated."
        )

    obs_year = _read_obs_year(ms_str)
    if obs_year is not None:
        casa_calls.append("tb.open(OBSERVATION) → TIME_RANGE (obs epoch)")

    # --- Pol terms from the catalogue (no CASA) ---
    # Resolve epoch to the concrete catalogue key actually used (so the response
    # reports e.g. '2019' rather than the caller's None). Leave epoch untouched
    # when the calibrator is absent — the fitter raises the clean lookup KeyError.
    from ms_inspect.util.pol_calibrators import lookup_pol

    _entry = lookup_pol(lookup_name)
    if _entry is not None:
        epoch = resolve_epoch(_entry, epoch, obs_year)
    try:
        polindex, polangle = fit_pol_terms_from_catalogue(
            lookup_name,
            reffreq_ghz=reffreq_ghz,
            epoch=epoch,
            pol_freq_range_ghz=pol_freq_range,
            polindex_deg=polindex_deg,
            polangle_deg=polangle_deg,
            obs_epoch_year=obs_year,
        )
    except KeyError as exc:
        raise ComputationError(f"Calibrator lookup failed: {exc}", ms_path=ms_path) from exc
    except ValueError as exc:
        raise ComputationError(f"Polarization fitting failed: {exc}", ms_path=ms_path) from exc

    script_path = str(workdir_path / "setjy_polcal.py")
    script_content = _build_script(
        ms_str,
        field,
        lookup_name,
        reffreq_ghz,
        polindex,
        polangle,
        min_chunk_mhz,
        str(workdir_path),
    )
    Path(script_path).write_text(script_content)
    casa_calls.append(f"write_script → {script_path}")

    # The fitter clamps each degree down to (in-band node count - 1) when the
    # requested degree exceeds the available nodes; the returned coefficient list
    # length encodes the effective degree. Surface it so a clamp is visible.
    eff_polindex_deg = len(polindex) - 1
    eff_polangle_deg = len(polangle) - 1
    if eff_polindex_deg < polindex_deg or eff_polangle_deg < polangle_deg:
        warnings.append(
            f"Fit degree clamped to in-band node count: "
            f"polindex {polindex_deg}→{eff_polindex_deg}, "
            f"polangle {polangle_deg}→{eff_polangle_deg} "
            f"(requested degree exceeded available nodes in band {pol_freq_range})."
        )

    base_data: dict = {
        "script_path": fmt_field(script_path),
        "calibrator": fmt_field(lookup_name),
        "epoch": epoch,
        "reffreq_ghz": reffreq_ghz,
        "min_chunk_mhz": min_chunk_mhz,
        "polindex": fmt_field(polindex),
        "polindex_c0": round(polindex[0], 6),
        "polindex_deg_used": eff_polindex_deg,
        "polangle": fmt_field(polangle),
        "polangle_c0_rad": round(polangle[0], 6),
        "polangle_deg_used": eff_polangle_deg,
        "stokes_i_source": "Perley-Butler 2017 (probed at run time)",
    }

    if not execute:
        warnings.append(
            f"Script written to {script_path}. Run it externally with CASA: it probes "
            "Perley-Butler Stokes I per SPW, fits flux/spix, then sets the manual model."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data=base_data,
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # --- execute=True: probe → fit → apply in-process ---
    try:
        from casatasks import setjy  # type: ignore[import]  # noqa: F401
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    freqs, fluxes, probe_calls = _probe_stokes_i_in_process(ms_str, field, min_chunk_mhz)
    casa_calls.extend(probe_calls)
    if not freqs:
        raise ComputationError(
            f"Perley-Butler probe returned no flux samples for field {field!r}.",
            ms_path=ms_path,
        )

    flux_at_ref, spix = fit_stokes_i_adaptive(freqs, fluxes, reffreq_ghz)
    if len(freqs) < 3:
        warnings.append(
            f"Only {len(freqs)} frequency sample(s) probed; spectral index fit is "
            f"degree {min(2, len(freqs) - 1)} (spix={spix}). Widen the band or lower "
            "min_chunk_mhz for a better Stokes I slope."
        )

    from casatasks import setjy  # type: ignore[import]

    casa_calls.append(
        f"casatasks.setjy(field='{field}', standard='manual', reffreq={reffreq_ghz}GHz)"
    )
    setjy(
        vis=ms_str,
        field=field,
        standard="manual",
        fluxdensity=[flux_at_ref, 0, 0, 0],
        spix=spix,
        reffreq=f"{reffreq_ghz}GHz",
        polindex=polindex,
        polangle=polangle,
        scalebychan=True,
        usescratch=True,
    )
    record_stage(
        str(workdir_path),
        "setjy_polcal",
        ms_str,
        {"flux_jy": float(flux_at_ref), "spix": spix, "n_probe_points": len(freqs)},
    )
    base_data["executed"] = True
    base_data["flux_jy"] = fmt_field(round(flux_at_ref, 4))
    base_data["spix"] = fmt_field(spix)
    base_data["n_probe_points"] = len(freqs)
    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data=base_data,
        warnings=warnings,
        casa_calls=casa_calls,
    )
