"""
split_average.py — ms_split_average

Splits calibrated target data (CORRECTED_DATA by default) to a new MS with
channel and time averaging, so imaging and selfcal run on fewer visibilities.

split never averages across scan or state boundaries (combine=''), so a time
bin longer than a scan only averages within the scan. The time bin is at most
MAX_TIMEBIN_S. The output MS must not exist: split refuses to overwrite it,
and an existing MS is never deleted by this tool.
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.exceptions import ComputationError
from ms_inspect.util.casa_context import validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import normalize_field_sel, response_envelope
from ms_inspect.util.stage_log import record_stage

TOOL_NAME = "ms_split_average"
STAGE = "split_average"

#: Longest time bin, in seconds, this tool will apply.
MAX_TIMEBIN_S = 30.0


def _split_kwargs(
    ms_str: str,
    output_ms: str,
    field: str,
    spw: str,
    width: list[int],
    timebin_s: float,
    datacolumn: str,
) -> dict:
    """Keyword arguments for casatasks.split, shared by both execution paths."""
    return {
        "vis": ms_str,
        "outputvis": output_ms,
        "field": field,
        "spw": spw,
        "datacolumn": datacolumn,
        "width": width[0] if len(width) == 1 else list(width),
        "timebin": f"{timebin_s:g}s" if timebin_s > 0 else "0s",
        "keepflags": False,
    }


def _build_script(kwargs: dict, workdir: str) -> str:
    """Return a self-contained split-with-averaging Python script."""
    from ms_inspect.util.stage_log import RECORD_STAGE_SNIPPET as record

    measurement = {"width": kwargs["width"], "timebin": kwargs["timebin"]}
    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_split_average (ms_modify).
Run with: python split_average.py
\"\"\"
from casatasks import split

{record}

split_kwargs = {kwargs!r}

split(**split_kwargs)
_record_stage({workdir!r}, {STAGE!r}, split_kwargs["outputvis"], {measurement!r})
print(f"Averaged split complete: {{split_kwargs['outputvis']}}")
"""


def run(
    ms_path: str,
    workdir: str,
    field: str,
    output_ms: str,
    width: list[int] | None = None,
    timebin_s: float = 0.0,
    spw: str = "",
    datacolumn: str = "corrected",
    execute: bool = False,
) -> dict:
    """
    Split target data to a new MS with channel and time averaging.

    Args:
        ms_path:    Path to the calibrated MS.
        workdir:    Existing output directory; output_ms must be inside it.
        field:      CASA field selection for the target (required).
        output_ms:  Path of the new MS. Must not exist.
        width:      Channels to average: one value for all SpWs, or one per selected SpW.
        timebin_s:  Time bin in seconds (0 = no time averaging, at most MAX_TIMEBIN_S).
        spw:        CASA SpW selection ('' = all).
        datacolumn: Column to split (default 'corrected').
        execute:    If False (default), write split_average.py and return.
                    If True, run split in-process.
    """
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []

    field = normalize_field_sel(field)
    if not field:
        raise ComputationError(
            "field is required: name the target field(s) to split.", ms_path=ms_path
        )
    width = list(width) if width else [1]
    if any(w < 1 for w in width):
        raise ComputationError(f"width values must be >= 1, got {width}.", ms_path=ms_path)
    if not 0.0 <= timebin_s <= MAX_TIMEBIN_S:
        raise ComputationError(
            f"timebin_s must be between 0 and {MAX_TIMEBIN_S:g} s, got {timebin_s:g}.",
            ms_path=ms_path,
        )

    workdir_path = Path(workdir).expanduser().resolve()
    if not workdir_path.exists():
        raise ComputationError(
            f"workdir does not exist: {workdir}. Create it before calling this tool.",
            ms_path=ms_path,
        )
    out = Path(output_ms).expanduser().resolve()
    if out == p:
        raise ComputationError("output_ms equals the input MS — refusing.", ms_path=ms_path)
    if workdir_path not in out.parents:
        raise ComputationError(
            f"output_ms {out} is not inside workdir {workdir_path}.", ms_path=ms_path
        )
    if out.exists():
        raise ComputationError(
            f"output_ms {out} already exists — refusing to overwrite. "
            "Choose a new name or remove it yourself.",
            ms_path=ms_path,
        )

    kwargs = _split_kwargs(ms_str, str(out), field, spw, width, timebin_s, datacolumn)
    script_path = workdir_path / "split_average.py"
    script_path.write_text(_build_script(kwargs, str(workdir_path)))
    casa_calls.append(f"write_script → {script_path}")

    data: dict = {
        "script_path": fmt_field(str(script_path)),
        "field": field,
        "spw": spw,
        "width": kwargs["width"],
        "timebin": kwargs["timebin"],
        "datacolumn": datacolumn,
        "output_ms": fmt_field(None, flag="UNAVAILABLE", note="script not yet executed"),
    }

    if not execute:
        warnings.append(f"Script written to {script_path}. Run it externally, then image {out}.")
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data=data,
            warnings=warnings,
            casa_calls=casa_calls,
        )

    try:
        from casatasks import split  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.", ms_path=ms_path
        ) from None

    casa_calls.append(f"casatasks.split(**{kwargs!r})")
    try:
        split(**kwargs)
    except Exception as exc:
        raise ComputationError(f"split to {out} failed: {exc}", ms_path=ms_path) from exc

    record_stage(
        str(workdir_path),
        STAGE,
        str(out),
        {"width": kwargs["width"], "timebin": kwargs["timebin"]},
    )
    data["output_ms"] = fmt_field(str(out))
    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data=data,
        warnings=warnings,
        casa_calls=casa_calls,
    )
