"""
split_average.py — ms_split_average

The average_target pipeline stage. Splits calibrated target data
(CORRECTED_DATA by default) to a new MS with channel and time averaging, so
imaging and selfcal run on fewer visibilities.

The stage always runs. With width=[1] and timebin_s=0 nothing is split: the
stage records that no averaging was applied and that imaging uses the source
MS. With averaging, the stage-log line marks the output MS as calibrated
target data held in its DATA column, which ms_workflow_status reads.

split never averages across scan or state boundaries (combine=''), so a time
bin longer than a scan only averages within the scan. The time bin is at most
MAX_TIMEBIN_S. The output MS must not exist: split refuses to overwrite it,
and an existing MS is never deleted by this tool.
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.exceptions import ComputationError
from ms_inspect.util.casa_context import validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import normalize_field_sel, response_envelope
from ms_inspect.util.stage_log import record_stage

TOOL_NAME = "ms_split_average"
STAGE = "split_average"

#: Longest time bin, in seconds, this tool will apply.
MAX_TIMEBIN_S = 30.0


def _split_kwargs(
    ms_str: str,
    output_ms: str,
    field: str,
    spw: str,
    width: list[int],
    timebin_s: float,
    datacolumn: str,
) -> dict:
    """Keyword arguments for casatasks.split, shared by both execution paths."""
    return {
        "vis": ms_str,
        "outputvis": output_ms,
        "field": field,
        "spw": spw,
        "datacolumn": datacolumn,
        "width": width[0] if len(width) == 1 else list(width),
        "timebin": f"{timebin_s:g}s" if timebin_s > 0 else "0s",
        "keepflags": False,
    }


def _build_script(kwargs: dict | None, product: str, measurement: dict, workdir: str) -> str:
    """Return a self-contained script; kwargs=None records the stage without a split."""
    from ms_inspect.util.stage_log import RECORD_STAGE_SNIPPET as record

    if kwargs is None:
        body = f'print("No averaging requested; image the source MS: " + {product!r})\n'
        imports = ""
    else:
        body = f"split_kwargs = {kwargs!r}\n\nsplit(**split_kwargs)\n"
        imports = "from casatasks import split\n"
    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_split_average (ms_modify).
Run with: python split_average.py
\"\"\"
{imports}
{record}

{body}_record_stage({workdir!r}, {STAGE!r}, {product!r}, {measurement!r})
"""


def run(
    ms_path: str,
    workdir: str,
    field: str,
    output_ms: str = "",
    width: list[int] | None = None,
    timebin_s: float = 0.0,
    spw: str = "",
    datacolumn: str = "corrected",
    execute: bool = False,
) -> dict:
    """
    Split target data to a new MS with channel and time averaging.

    Args:
        ms_path:    Path to the calibrated MS.
        workdir:    Existing output directory; output_ms must be inside it.
        field:      CASA field selection for the target (required).
        output_ms:  Path of the new MS. Must not exist. Required when averaging;
                    ignored when width=[1] and timebin_s=0.
        width:      Channels to average: one value for all SpWs, or one per selected SpW.
        timebin_s:  Time bin in seconds (0 = no time averaging, at most MAX_TIMEBIN_S).
        spw:        CASA SpW selection ('' = all).
        datacolumn: Column to split (default 'corrected').
        execute:    If False (default), write split_average.py and return.
                    If True, run in-process.
    """
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []

    field = normalize_field_sel(field)
    if not field:
        raise ComputationError(
            "field is required: name the target field(s) to split.", ms_path=ms_path
        )
    width = list(width) if width else [1]
    if any(w < 1 for w in width):
        raise ComputationError(f"width values must be >= 1, got {width}.", ms_path=ms_path)
    if not 0.0 <= timebin_s <= MAX_TIMEBIN_S:
        raise ComputationError(
            f"timebin_s must be between 0 and {MAX_TIMEBIN_S:g} s, got {timebin_s:g}.",
            ms_path=ms_path,
        )

    workdir_path = Path(workdir).expanduser().resolve()
    if not workdir_path.exists():
        raise ComputationError(
            f"workdir does not exist: {workdir}. Create it before calling this tool.",
            ms_path=ms_path,
        )

    averaged = any(w > 1 for w in width) or timebin_s > 0
    kwargs: dict | None = None
    if averaged:
        if not output_ms:
            raise ComputationError(
                "output_ms is required when averaging (width > 1 or timebin_s > 0).",
                ms_path=ms_path,
            )
        out = Path(output_ms).expanduser().resolve()
        if out == p:
            raise ComputationError("output_ms equals the input MS — refusing.", ms_path=ms_path)
        if workdir_path not in out.parents:
            raise ComputationError(
                f"output_ms {out} is not inside workdir {workdir_path}.", ms_path=ms_path
            )
        if out.exists():
            raise ComputationError(
                f"output_ms {out} already exists — refusing to overwrite. "
                "Choose a new name or remove it yourself.",
                ms_path=ms_path,
            )
        kwargs = _split_kwargs(ms_str, str(out), field, spw, width, timebin_s, datacolumn)
        product = str(out)
        measurement = {
            "averaged": True,
            "source_ms": ms_str,
            "field": field,
            "datacolumn": datacolumn,
            "width": kwargs["width"],
            "timebin": kwargs["timebin"],
        }
    else:
        product = ms_str
        measurement = {"averaged": False, "source_ms": ms_str, "field": field}
        warnings.append(
            f"No averaging requested (width=[1], timebin_s=0). The stage is recorded; "
            f"image {ms_str} directly."
        )

    script_path = workdir_path / "split_average.py"
    script_path.write_text(_build_script(kwargs, product, measurement, str(workdir_path)))
    casa_calls.append(f"write_script → {script_path}")

    data: dict = {
        "script_path": fmt_field(str(script_path)),
        "averaged": averaged,
        "field": field,
        "spw": spw,
        "width": kwargs["width"] if kwargs else 1,
        "timebin": kwargs["timebin"] if kwargs else "0s",
        "datacolumn": datacolumn,
        "image_ms": (
            fmt_field(product, flag="UNAVAILABLE", note="script not yet executed")
            if averaged
            else fmt_field(product)
        ),
    }

    if not execute:
        warnings.append(f"Script written to {script_path}. Run it, then image {product}.")
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data=data,
            warnings=warnings,
            casa_calls=casa_calls,
        )

    if kwargs is not None:
        try:
            from casatasks import split  # type: ignore[import]
        except ImportError:
            from ms_inspect.exceptions import CASANotAvailableError

            raise CASANotAvailableError(
                "casatasks is not installed or cannot be imported.", ms_path=ms_path
            ) from None

        casa_calls.append(f"casatasks.split(**{kwargs!r})")
        try:
            split(**kwargs)
        except Exception as exc:
            raise ComputationError(f"split to {product} failed: {exc}", ms_path=ms_path) from exc

    record_stage(str(workdir_path), STAGE, product, measurement)
    data["image_ms"] = fmt_field(product)
    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data=data,
        warnings=warnings,
        casa_calls=casa_calls,
    )
