"""
tclean.py — ms_tclean

Generate a first-pass imaging script using CASA tclean.

All imaging parameters are accepted explicitly — no parameter derivation
is done inside this tool. See skill 11-imaging.md for derivation logic.

When execute=False (default), writes a self-contained script to
workdir/tclean_<imagename_stem>.py and returns immediately. Run it
externally as a background job; tclean on a real mosaic can take hours.
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.util.casa_context import open_table, validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import normalize_field_sel, response_envelope
from ms_inspect.util.stage_log import record_stage
from ms_modify.exceptions import TcleanFailedError

TOOL_NAME = "ms_tclean"

# Global tclean stopcodes (casatasks imager_deconvolver). Converged = {2, 8}.
_STOPCODE_DESC = {
    1: "iteration limit reached before threshold",
    2: "threshold reached",
    3: "force stop",
    4: "no change in peak residual across two major cycles",
    5: "peak residual diverging (>3x previous major cycle)",
    6: "peak residual diverging (>3x minimum reached)",
    7: "zero mask (nothing to deconvolve)",
    8: "n-sigma / combined exit criterion",
}
_CONVERGED_STOPCODES = {2, 8}


def _convergence(summary: object) -> tuple[int | None, str, bool, str | None]:
    """(stopcode, description, converged, warning) from a tclean summary dict."""
    if not isinstance(summary, dict) or "stopcode" not in summary:
        return (
            None,
            "unknown",
            False,
            ("tclean returned no summary dict; convergence could not be verified."),
        )
    code = int(summary["stopcode"])
    desc = _STOPCODE_DESC.get(code, f"unrecognized stopcode {code}")
    if code in _CONVERGED_STOPCODES:
        return code, desc, True, None
    return (
        code,
        desc,
        False,
        (
            f"tclean did NOT converge: stopcode {code} ({desc}). Restored image is "
            "likely deconvolution/sidelobe-limited, not a clean detection — inspect "
            "before reporting."
        ),
    )


def _script_path(workdir: Path, imagename: str) -> Path:
    stem = Path(imagename).name.replace(".", "_")
    return workdir / f"tclean_{stem}.py"


def _build_script(
    workdir: str,
    ms_str: str,
    imagename: str,
    field: str,
    spw: str,
    stokes: str,
    specmode: str,
    deconvolver: str,
    nterms: int | None,
    gridder: str,
    wprojplanes: int | None,
    cfcache: str | None,
    cell: str,
    imsize: list[int],
    weighting: str,
    robust: float,
    niter: int,
    threshold: str,
    savemodel: str,
    pblimit: float,
    nchan: int | None,
    start: str | None,
    width: str | None,
    outframe: str | None,
) -> str:
    # Same rule the execute=True path uses at the bottom of run(): mtmfs with
    # nterms writes Taylor terms, so there is no plain .image to record.
    is_mtmfs = deconvolver == "mtmfs" and nterms is not None
    optional_lines = ""
    if spw:
        optional_lines += f"    spw          = {spw!r},\n"
    if deconvolver == "mtmfs" and nterms is not None:
        optional_lines += f"    nterms       = {nterms},\n"
    if wprojplanes is not None:
        optional_lines += f"    wprojplanes  = {wprojplanes},\n"
    if cfcache is not None:
        optional_lines += f"    cfcache      = {cfcache!r},\n"
    # Cube channelization — only meaningful for specmode='cube'.
    if specmode == "cube":
        if nchan is not None:
            optional_lines += f"    nchan        = {nchan},\n"
        if start is not None:
            optional_lines += f"    start        = {start!r},\n"
        if width is not None:
            optional_lines += f"    width        = {width!r},\n"
        if outframe is not None:
            optional_lines += f"    outframe     = {outframe!r},\n"

    script_name = Path(imagename).name.replace(".", "_")

    from ms_inspect.util.stage_log import RECORD_STAGE_SNIPPET as record

    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_tclean (ms_modify).
Run with: python tclean_{script_name}.py
\"\"\"
import glob
import os
import shutil
from casatasks import tclean

ms_path   = {ms_str!r}
{record}
workdir = {workdir!r}

imagename = {imagename!r}

# Remove existing tclean products for this imagename before re-running.
# Only known product suffixes are removed — never a bare glob of
# imagename + ".*", which could match the MS itself or unrelated files.
_PRODUCT_SUFFIXES = (
    ".image", ".residual", ".psf", ".pb", ".model", ".sumwt", ".mask",
    ".pbcor", ".weight", ".gridwt", ".workdirectory",
)
for p in glob.glob(imagename + ".*"):
    rest = p[len(imagename):]
    is_product = any(
        rest == s or rest[: len(s) + 1] == s + "." for s in _PRODUCT_SUFFIXES
    )
    if not is_product:
        continue
    if os.path.isdir(p):
        shutil.rmtree(p)
    elif os.path.isfile(p):
        os.remove(p)

summary = tclean(
    vis          = ms_path,
    imagename    = imagename,
    field        = {field!r},
    stokes       = {stokes!r},
    specmode     = {specmode!r},
    deconvolver  = {deconvolver!r},
{optional_lines}    gridder      = {gridder!r},
    cell         = [{cell!r}],
    imsize       = {imsize!r},
    weighting    = {weighting!r},
    robust       = {robust},
    niter        = {niter},
    threshold    = {threshold!r},
    pbcor        = True,
    pblimit      = {pblimit},
    savemodel    = {savemodel!r},
    fullsummary  = False,
)
_code = summary.get("stopcode") if isinstance(summary, dict) else None
_desc = {{
    1: "iteration limit reached before threshold", 2: "threshold reached",
    3: "force stop", 4: "no change in peak residual",
    5: "diverging (>3x prev major cycle)", 6: "diverging (>3x minimum)",
    7: "zero mask", 8: "n-sigma / combined",
}}.get(_code, "unknown")
# The image existing is not success: a clean that stopped on the iteration
# limit, or diverged, is deconvolution-limited rather than a detection. tclean
# does return a summary, so the stopcode is read rather than measured — record
# it beside the product so the record says which kind of stop this was.
_image = imagename + (".image.tt0" if {is_mtmfs} else ".image")
_record_stage(
    workdir,
    "tclean",
    _image,
    {{"stopcode": _code, "converged": _code in (2, 8)}},
)
if _code in (2, 8):
    print(f"tclean CONVERGED (stopcode={{_code}}: {{_desc}}):", imagename)
else:
    print(f"tclean DID NOT CONVERGE (stopcode={{_code}}: {{_desc}}) -- image likely "
          "deconvolution-limited, not a clean detection:", imagename)
"""


def run(
    ms_path: str,
    imagename: str,
    field: str,
    workdir: str,
    spw: str = "",
    stokes: str = "I",
    specmode: str = "mfs",
    deconvolver: str = "hogbom",
    nterms: int | None = None,
    gridder: str = "standard",
    wprojplanes: int | None = None,
    cfcache: str | None = None,
    cell: str = "1.0arcsec",
    imsize: list[int] | None = None,
    weighting: str = "briggs",
    robust: float = 0.5,
    niter: int = 50000,
    threshold: str = "1.0mJy",
    savemodel: str = "modelcolumn",
    pblimit: float = -0.01,
    nchan: int | None = None,
    start: str | None = None,
    width: str | None = None,
    outframe: str | None = None,
    execute: bool = False,
) -> dict:
    """
    Generate (and optionally execute) a tclean imaging script.

    Validates that CORRECTED_DATA exists in the MS before writing the script.
    pbcor=True is always set — primary beam correction is applied by tclean.

    Args:
        ms_path:     Path to the full Measurement Set.
        imagename:   Base name for all output image products (no suffix).
        field:       CASA field selection for science target(s).
        workdir:     Existing directory for script and image output.
        spw:         CASA SPW selection (default '' = all SPWs). Use to drop
                     RFI-dominated SPWs, e.g. '0~8,10~15' to exclude SPW 9.
        stokes:      Stokes products to image (default 'I').
        specmode:    'mfs', 'cube', or 'mvc' (default 'mfs'). Use 'mvc' with
                     gridder='awp2' — awp2 does not implement conjbeams, and
                     plain 'mfs' needs several major cycles to converge the
                     wideband flux normalization.
        deconvolver: 'hogbom' or 'mtmfs' (default 'hogbom').
        nterms:      Taylor terms for mtmfs (default None; pass 2 for mtmfs).
        gridder:     'standard', 'wproject', or 'awp2' (default 'standard').
        wprojplanes: W-projection planes (None = omit; set for wproject/awp2
                     when W-terms are required per Fresnel criterion). If
                     omitted for those gridders, CASA silently defaults to 1
                     (no W-projection) — a warning is emitted in the response.
        cfcache:     Convolution-function cache path. Applies to
                     gridder='awproject' only (awp2 does not use a cfcache).
                     Without it, awproject recomputes CFs from scratch on
                     every run — potentially many hours.
        cell:        Cell size string, e.g. '2.5arcsec'.
        imsize:      Image size as [nx, ny] (default [512, 512]).
        weighting:   UV weighting scheme (default 'briggs').
        robust:      Briggs robust parameter (default 0.5).
        niter:       Maximum clean iterations (default 50000).
        threshold:   Clean stopping threshold, e.g. '0.5mJy'.
        pblimit:     Primary-beam gain cutoff. Default -0.01 (negative disables
                     PB-based blanking, so low-gain regions and sources out in
                     the PB sidelobes stay visible in the image — important for
                     spotting outliers). CASA's own default is 0.2, which blanks
                     everything below 20% PB.
        savemodel:   'modelcolumn' writes MODEL_DATA for self-cal (default).
        nchan:       Number of output channels for the cube (specmode='cube'
                     only; None = all). For a polarization frequency cube,
                     one plane per SPW-chunk per skill 11.
        start:       First channel of the cube as a CASA spectral string, e.g.
                     '1.0GHz' or '0' (specmode='cube' only).
        width:       Channel width of the cube, e.g. '64MHz' or '4'
                     (specmode='cube' only).
        outframe:    Output spectral reference frame, e.g. 'LSRK' (specmode=
                     'cube' only). None lets CASA default.
        execute:     If False (default), write script and return.
                     If True, run tclean in-process (intended for test data only).

    Returns:
        Standard response envelope with script_path always present.
        When execute=True, also includes imagename and completed flag.
    """
    field = normalize_field_sel(field)
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    warnings: list[str] = []
    casa_calls: list[str] = []

    if imsize is None:
        imsize = [512, 512]

    if gridder in ("wproject", "awp2", "awproject") and wprojplanes is None:
        warnings.append(
            f"gridder='{gridder}' with wprojplanes unset: CASA defaults to "
            "wprojplanes=1 (no W-projection). Pass wprojplanes explicitly if "
            "W-terms are significant (Fresnel < 0.9)."
        )

    # awproject-family full-polarization guardrails (warn-only). Both are real
    # CASA 6.7.5 costs/limits seen across three reduction runs, not tool bugs —
    # the value is steering the parameter choice, so tclean still emits exactly
    # what was asked.
    _is_awp = gridder in ("awp2", "awproject")
    _is_fullpol = bool(set(stokes.upper()) & {"Q", "U", "V"})
    if _is_awp and _is_fullpol and deconvolver == "mtmfs" and specmode == "mvc":
        warnings.append(
            f"gridder='{gridder}' + stokes='{stokes}' + deconvolver='mtmfs' + "
            "specmode='mvc' trips a CASA 6.7.5 shape assertion "
            "(AlwaysAssert shapeIn.isEqual(shapeOut), Lattice.tcc) in the "
            "mtmfs-via-cube PSF Taylor-term path — it dies during PSF creation "
            "before any cleaning. To keep multi-term (Taylor) deconvolution, set "
            "specmode='mfs' with deconvolver='mtmfs'."
        )
    if _is_awp and _is_fullpol:
        warnings.append(
            f"gridder='{gridder}' + stokes='{stokes}': the per-frequency A-term "
            "convolution-function computation (full Mueller CF for full-pol) can "
            "be intractable on a large unaveraged MS — e.g. ~1 h to reach 20% of "
            "just the PSF on a ~160 GB MS. Consider split/time-averaging to a "
            "compact MS first, or gridder='wproject' (image-plane pbcor) for a "
            "near-axis single pointing."
        )
    if cfcache is not None and gridder != "awproject":
        warnings.append(f"cfcache is only used by gridder='awproject'; ignored for '{gridder}'.")
    if gridder == "awproject" and cfcache is None:
        warnings.append(
            "gridder='awproject' without cfcache: convolution functions will be "
            "recomputed from scratch (potentially hours). Set cfcache to a "
            "persistent path to reuse them across runs."
        )
    if specmode != "cube" and any(v is not None for v in (nchan, start, width, outframe)):
        warnings.append(
            f"specmode='{specmode}': cube args (nchan/start/width/outframe) are "
            "ignored. Set specmode='cube' to image a frequency cube."
        )

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"workdir does not exist: {workdir}",
            ms_path=ms_path,
        )

    # Verify CORRECTED_DATA column exists.
    # Open failure (casatools not installed, table locked) is non-fatal — add a warning.
    # Missing column is always fatal — tclean on uncalibrated data is a silent science error.
    col_names: list[str] = []
    try:
        with open_table(ms_str) as tb:
            col_names = list(tb.colnames())
        casa_calls.append("tb.open(MS) → colnames() [CORRECTED_DATA check]")
    except Exception as exc:
        warnings.append(f"Could not verify CORRECTED_DATA column: {exc}")

    if col_names and "CORRECTED_DATA" not in col_names:
        from ms_inspect.exceptions import InsufficientMetadataError

        raise InsufficientMetadataError(
            "CORRECTED_DATA column not found in MS. Run ms_applycal before imaging.",
            ms_path=ms_path,
        )

    script_file = _script_path(workdir_path, imagename)
    script_content = _build_script(
        workdir=str(workdir_path),
        ms_str=ms_str,
        imagename=imagename,
        field=field,
        spw=spw,
        stokes=stokes,
        specmode=specmode,
        deconvolver=deconvolver,
        nterms=nterms,
        gridder=gridder,
        wprojplanes=wprojplanes,
        cfcache=cfcache if gridder == "awproject" else None,
        cell=cell,
        imsize=imsize,
        weighting=weighting,
        robust=robust,
        niter=niter,
        threshold=threshold,
        savemodel=savemodel,
        pblimit=pblimit,
        nchan=nchan,
        start=start,
        width=width,
        outframe=outframe,
    )
    script_file.write_text(script_content)
    casa_calls.append(f"write_script → {script_file}")

    if not execute:
        data = {
            "script_path": fmt_field(str(script_file)),
            "imagename": fmt_field(imagename),
            "completed": fmt_field(False, note="script not yet executed"),
        }
        warnings.append(
            f"Script written to {script_file}. Run it externally as a background job; "
            "tclean on real data can take hours."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data=data,
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True: run tclean in-process.
    try:
        from casatasks import tclean as _tclean  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed.",
            ms_path=ms_path,
        ) from None

    tclean_kwargs: dict = dict(
        vis=ms_str,
        imagename=imagename,
        field=field,
        stokes=stokes,
        spw=spw,
        specmode=specmode,
        deconvolver=deconvolver,
        gridder=gridder,
        cell=[cell],
        imsize=imsize,
        weighting=weighting,
        robust=robust,
        niter=niter,
        threshold=threshold,
        pbcor=True,
        pblimit=pblimit,
        savemodel=savemodel,
        fullsummary=False,
    )
    if deconvolver == "mtmfs" and nterms is not None:
        tclean_kwargs["nterms"] = nterms
    if wprojplanes is not None:
        tclean_kwargs["wprojplanes"] = wprojplanes
    if cfcache is not None and gridder == "awproject":
        tclean_kwargs["cfcache"] = cfcache
    if specmode == "cube":
        if nchan is not None:
            tclean_kwargs["nchan"] = nchan
        if start is not None:
            tclean_kwargs["start"] = start
        if width is not None:
            tclean_kwargs["width"] = width
        if outframe is not None:
            tclean_kwargs["outframe"] = outframe

    casa_calls.append(f"casatasks.tclean(imagename={imagename!r}, ...)")
    try:
        summary = _tclean(**tclean_kwargs)
    except Exception as exc:
        raise TcleanFailedError(
            f"tclean raised: {exc}",
            ms_path=ms_path,
        ) from exc

    # mtmfs (nterms>1) writes Taylor-term images: .image.tt0, .image.tt1, ...
    # There is no plain .image in that case, so check the tt0 product.
    if deconvolver == "mtmfs" and nterms is not None:
        image_path = imagename + ".image.tt0"
    else:
        image_path = imagename + ".image"
    completed = Path(image_path).exists()
    if not completed:
        raise TcleanFailedError(
            f"tclean completed without error but {image_path} was not created.",
            ms_path=ms_path,
        )

    # Existence of the image is not success: a clean that stopped on the
    # iteration limit (or diverged) is deconvolution-limited, not a detection.
    stopcode, stop_reason, converged, conv_warn = _convergence(summary)
    if conv_warn:
        warnings.append(conv_warn)
    record_stage(
        str(workdir_path),
        "tclean",
        image_path,
        {"stopcode": stopcode, "converged": converged},
    )

    data = {
        "script_path": fmt_field(str(script_file)),
        "imagename": fmt_field(imagename),
        "completed": fmt_field(completed),
        "converged": fmt_field(
            converged, flag="COMPLETE" if stopcode is not None else "UNAVAILABLE"
        ),
        "stopcode": fmt_field(stopcode),
        "stop_reason": fmt_field(stop_reason),
    }
    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data=data,
        warnings=warnings,
        casa_calls=casa_calls,
    )
